# Align function parameters and arguments vertically for better readability.
fn_params_layout = "Vertical"

# Maximum width of a line. Helps keep the code readable.
max_width = 100

# Indent wrapped function arguments and method chains.
indent_style = "Visual"

# Add trailing commas where possible. Helps with cleaner diffs.
trailing_comma = "Always"

# Use spaces instead of tabs for indentation.
hard_tabs = false

# Number of spaces per indentation level.
tab_spaces = 4

# Use vertical layout for struct and enum fields when they exceed max_width.
struct_field_align_threshold = 40
enum_discrim_align_threshold = 40

# Force braces on the same line for function declarations.
fn_brace_style = "SameLineWhere"
